  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[main]]
  name = "Gallery"
  weight = 400
  identifier = "gallery"
  url = "/gallery/"

  [[main]]
  name = "Photgraphy"
  weight = 500
  identifier = "photography"
  url = "/photography/"

  [[main]]
  name = "Projects"
  weight = 600
  identifier = "projects"
  url = "/projects/"


  [[footer]]
  name = "adammusciano.com"
  weight = 1
  identifier = "adammusciano.com"
  url = "https://adammusciano.com"